apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: suppr
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/home-cluster/apps/suppr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
